# -*- mode: ruby -*-
# vi: set ft=ruby :

  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
# end

hosts = {
  "test-web" => "192.168.56.11",
  "test-app" => "192.168.56.12",
}

Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/bionic64"
  config.vm.box_check_update = false

  hosts.each do |name, ip|
    config.vm.define name do |machine|

      machine.vm.hostname = name

      machine.vm.network :private_network, ip: ip
      machine.vm.network :public_network

      machine.vm.provider "virtualbox" do |v|

        v.name = name
        v.gui = false
        v.memory = "1024"
        v.cpus = 1

      end

    end

  end

end
